app:
  name: webnext
  image:
    repository: dangelomagallanes/pokeapi_next_finalizado
    tag: latest
    pullPolicy: Always
  container:
    name: webnext
    port: 80
    replicas: 2
  service:
    type: NodePort
    port: 80
    nodePort: 30087
    sshPort: 3456
    sshTargetPort: 3456
    sshNodePort: 30457
  ingress:
    host: pokeapi.dangelomagallanes.me
    port: 80
