createNamespace: false

app:
  name: webnext
  image:
    repository: dangekid/pokeapi_next_finalizado
    tag: latest
    pullPolicy: Always
  container:
    name: webnext
    port: 80
    replicas: 2
  service:
    type: NodePort
    port: 80
    nodePort: 30087
  ingress:
    enabled: true
    host: pokeapi.dangelomagallanes.me
    port: 80
  readiness:
    initialDelaySeconds: 120
    periodSeconds: 10
    timeoutSeconds: 5
