apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.container.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.container.name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.container.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.app.container.port }}
            initialDelaySeconds: {{ .Values.app.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.app.readiness.timeoutSeconds }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.app.container.port }}
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 10
