services:
  web:
    build:
      context: /home/dangelo/HLC-NEST-POSTSQL/docker/dangelomagallanes/
      dockerfile: ./dockerfiles/ubseguridad/damgubseguridad
      args:
        - INICIALES=damg
    container_name: ctdamgseguridad
    image: dangelomagallanes/ubseguridad
    ports:
      - 25:22
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      pseguridad_network:
        ipv4_address: 192.168.21.3
networks:
  pseguridad_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.21.0/24
