apiVersion: v1
kind: Secret
metadata:
  name: pokemon-secret
  namespace: proyecto-nest
type: Opaque
stringData:
  POSTGRES_USER: pokemonuser
  POSTGRES_PASSWORD: pokemonpass123
  POSTGRES_DB: pokemondb
