apiVersion: v1
kind: ConfigMap
metadata:
  name: postgre-configmap
  namespace: {{ .Release.Namespace }}
data:
  POSTGRES_HOST: postgre-service
  POSTGRES_PORT: "{{ .Values.postgres.service.port }}"
  POSTGRES_DB: {{ .Values.postgres.auth.database }}
