apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.app.container.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z postgre-service {{ .Values.postgres.service.port }}; do echo "Esperando PostgreSQL..."; sleep 3; done; echo "PostgreSQL listo!"']
      containers:
      - name: {{ .Values.app.container.name }}
        image: {{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}
        imagePullPolicy: {{ .Values.app.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.app.container.port }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.app.container.port }}
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
        livenessProbe:
          tcpSocket:
            port: {{ .Values.app.container.port }}
          initialDelaySeconds: 120
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: postgre-configmap
              key: POSTGRES_HOST
        - name: DB_PORT
          value: "{{ .Values.app.env.DB_PORT }}"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgre-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgre-secret
              key: POSTGRES_PASSWORD
        - name: DATABASE
          valueFrom:
            secretKeyRef:
              name: postgre-secret
              key: POSTGRES_DB
        - name: PORT
          value: "{{ .Values.app.env.PORT }}"
