apiVersion: v1
kind: Secret
metadata:
  name: postgre-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.auth.username }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password }}
  POSTGRES_DB: {{ .Values.postgres.auth.database }}
