apiVersion: v1
kind: Service
metadata:
  name: nest-taller
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app: {{ .Values.app.name }}
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.container.port }}
      nodePort: {{ .Values.app.service.nodePort }}
