apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres.name }}-statefulset
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: postgre-service
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }}
    spec:
      containers:
      - name: {{ .Values.postgres.name }}
        image: {{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}
        imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.postgres.service.port }}
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgre-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgre-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgre-secret
              key: POSTGRES_DB
        volumeMounts:
        - name: postgre-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgre-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      {{- if .Values.postgres.persistence.storageClassName }}
      storageClassName: {{ .Values.postgres.persistence.storageClassName }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.postgres.persistence.size }}
