services:
  web:
    build:
      context: /home/dangelo/HLC-NEST-POSTSQL/docker/dangelomagallanes/
      dockerfile: ./dockerfiles/ubbase/damgubbase
      args:
        - INICIALES=damg
    container_name: ctdamgbase
    image: dangelomagallanes/ubbase
    ports:
      - 22:22
    env_file:
      - ./.env
    volumes:
      - ./logs:/root/logs
    networks:
      pbase_network:
        ipv4_address: 192.168.20.3
networks:
  pbase_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
