services:
  web:
    build:
      context: /home/dangelo/HLC-NEST-POSTSQL/docker/dangelomagallanes/
      dockerfile: ./dockerfiles/postgre/damgpostgre
      args:
        - INICIALES=damg
    container_name: ctdamgpostgre
    image: dangelomagallanes/postgre
    ports:
      - 5432:5432
    volumes:
      - ./logs:/root/logs
    networks:
      ppostgre_network:
        ipv4_address: 192.168.27.3
networks:
  ppostgre_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.27.0/24
